<template>
<div class="holder col-8 col-lg-6 p-0">
    <!-- the @submit calls the method addItem on submit 
        .prevent blocks render, so animations can be played-->
    <form @submit.prevent="addItem">
        <!-- v-bind:class can change class on variable condition -->
        <input type="text" autocomplete="off" placeholder="Enter an item to add.." v-model="item" name="item" v-bind:class="!items[0] ? 'shadow' : ''">
        <!-- transition is used when animating content with css -->
        <transition name="alert-in" enter-active-class="animated flipInX" leave-active-class="animated flipOutX">
            <!-- this errors is generated by vee-validate, which is an imported component -->
            <p class="alert" v-if="validate">{{ error }}</p>
        </transition>
    </form>
    <!-- transition-group is used in conjunction with v-for -->
    <transition-group tag="ul" name="list" enter-active-class="animated slideInUp" leave-active-class="animated slideOutDown">
        <!-- for some reason transition-group won't work 
                unless key index is / 1, this is a known issue
                v-for loops through items, and create a <li> for every item -->
        <li v-for="(list, index) in items" :key='index / 1'
        class="d-flex align-items-center justify-content-between shadow">
            {{index + 1}}: {{ list.item }}
            <i class="fa fa-minus-circle" v-on:click="removeItem(list.key)"></i>
        </li>
    </transition-group>
</div>
</template>

<!-- You can split the .vue file into seperate files
    but you have to link the files into the template -->

<script src="./TodoList.js"></script>

<!-- Add "scoped" attribute to limit CSS to this component only -->

<style src="./TodoList.css" scoped></style>
